spring:
  datasource:
    name: easy_spring
    url: jdbc:mysql://localhost:3306/ly_db?useSSL=true
    username: lydata
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#    dbcp2:
#      min-idle: 1
#      max-idle: 2
#      initial-size: 1
#      time-between-eviction-runs-millis: 3000
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT "ZTM" FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false


mybatis:
  mapper-locations: classpath:mapper/UserMapper.xml,classpath:mapper/StudentMapper.xml
  