spring: 
  datasource:
    name: easy_spring
    url: jdbc:mysql://120.79.233.202:3306/enjoydb?useSSL=true
    username: 账户
    password: 密码
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp

server:
  servlet: 
    context-path: /ssm
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/UserMapper.xml,classpath:mapper/StudentMapper.xml

